#ifndef CONSTANT_H
#define CONSTANT_H

//Sever Class
#define PI 3.1415926535897932384626
#define CROSSING_MARK_LENGTH 40
#define WINDOW_HEIGHT 600
#define WINDOW_WIDTH 800
#define REFRESH_INTERVAL 250
#define CURSOR_INTERVAL 16
#define TIMER_REFRESH 1
#define TIMER_CURSOR 2
#define MAX_RECORD 10
#define UI_LEFT 275
#define UI_TOP 50
#define UI_RIGHT 775
#define UI_BOTTOM 331.25
#define BENCHMARK_Z 1
#define BENCHMARK_X 0.24
#define BENCHMARK_Y 0.12
#define CURSOR_NORMAL_RADIUS 2
#define CURSOR_CLICK_RADIUS 4
#define MAX_SENSOR 10
#define ZERO 1e-6
#define MAX_ITERATION 50000
#define MAX_FRAME_LENGTH 750
#define BODY_LENGTH 25
#define KINECT_FRAME_FREQ 40
#define IDB_CALIBRATION 2001
#define IDE_MARKDISTANCE 3001
#define TIMER_WINDOW_REFRESH 1
#define WINDOW_REFRESH_INTERVAL 40


#define TIMING_MESSAGE 1
#define TRILATERATION_MESSAGE 2
#define CALIBRATION_MESSAGE 3
#define HALT_MESSAGE 4
#define SENT_END_CALIBRATION_MESSAGE 2

//vision class
#define DISPLAY_HEIGHT 500
#define DISPLAY_WIDTH 400
#define DEFAULT_CIRCLE_RADIUS 10
#define DEFAULT_DISTANCE 150
#define PEN_SIZE 2


#endif